In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
df = pd.read_csv("Direct.csv")

In [3]:
df.head(15)

,plntname,ra_str,ra,dec_str,dec,imdelthmag,imdeltjmag,imdeltkmag,imdeltlpmag,imangsep,...,glon,glat,imjmag,imhmag,imkmag,imlpmag,implnjmag,implnhmag,implnkmag,implnlpmag
0,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,14.43,14.4,NaN,11.6,0.449,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,19.1,19.20,NaN,16.2
1,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,14.43,14.4,NaN,11.6,0.449,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,19.1,19.20,NaN,16.2
2,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,14.43,NaN,NaN,NaN,0.449,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,NaN,19.20,NaN,NaN
3,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,NaN,14.3,NaN,NaN,0.453,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,19.1,NaN,NaN,NaN
4,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,14.50,NaN,NaN,NaN,0.461,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,NaN,19.27,NaN,NaN
5,51 Eri b,04:37:36.13,69.400551,-02:28:24.8,-2.473548,NaN,NaN,NaN,11.6,0.461,...,198.61262,-30.657612,4.74,4.77,4.54,4.54,NaN,NaN,NaN,16.2
6,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
7,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
8,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
9,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
10,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
11,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,10.0,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,16.8,NaN
12,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,NaN,NaN,10.0,NaN,0.829,...,308.17875,11.029184,6.83,6.85,6.77,NaN,NaN,NaN,16.8,NaN
13,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,11.14,12.7,NaN,NaN,0.828,...,308.17875,11.029184,6.83,6.85,6.77,NaN,19.5,17.99,NaN,NaN
14,HIP 65426 b,13:24:36.10,201.150406,-51:30:16.1,-51.504459,NaN,NaN,NaN,NaN,0.830,...,308.17875,11.029184,6.83,6.85,6.77,NaN,NaN,NaN,NaN,NaN

In [4]:
print(df.size)
df.shape

8075

(323, 25)

In [5]:
df1 = df.dropna()

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   plntname     0 non-null      object
 1   ra_str       0 non-null      object
 2   ra           0 non-null      float64
 3   dec_str      0 non-null      object
 4   dec          0 non-null      float64
 5   imdelthmag   0 non-null      float64
 6   imdeltjmag   0 non-null      float64
 7   imdeltkmag   0 non-null      float64
 8   imdeltlpmag  0 non-null      float64
 9   imangsep     0 non-null      float64
 10  imsep        0 non-null      float64
 11  imtruesep    0 non-null      float64
 12  impa         0 non-null      float64
 13  imdist       0 non-null      float64
 14  ns           0 non-null      int64
 15  glon         0 non-null      float64
 16  glat         0 non-null      float64
 17  imjmag       0 non-null      float64
 18  imhmag       0 non-null      float64
 19  imkmag       0 non-null      float64
 20  imlpmag      0 non-null      float64
 21  implnjmag    0 non-null      float64
 22  implnhmag    0 non-null      float64
 23  implnkmag    0 non-null      float64
 24  implnlpmag   0 non-null      float64
dtypes: float64(21), int64(1), object(3)
memory usage: 0.0+ bytes

In [7]:
column_names = df1.columns
print(column_names)

Index(['plntname', 'ra_str', 'ra', 'dec_str', 'dec', 'imdelthmag',
       'imdeltjmag', 'imdeltkmag', 'imdeltlpmag', 'imangsep', 'imsep',
       'imtruesep', 'impa', 'imdist', 'ns', 'glon', 'glat', 'imjmag', 'imhmag',
       'imkmag', 'imlpmag', 'implnjmag', 'implnhmag', 'implnkmag',
       'implnlpmag'],
      dtype='object')

In [8]:
df1.head(15)

Empty DataFrame
Columns: [plntname, ra_str, ra, dec_str, dec, imdelthmag, imdeltjmag, imdeltkmag, imdeltlpmag, imangsep, imsep, imtruesep, impa, imdist, ns, glon, glat, imjmag, imhmag, imkmag, imlpmag, implnjmag, implnhmag, implnkmag, implnlpmag]
Index: []

[0 rows x 25 columns]

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [10]:
# Select relevant features and target variable
features = df1[['pl_orbper', 'pl_rade', 'pl_orbeccen', 'pl_orbincl', 'pl_tranmid', 'pl_imppar', 'pl_trandep', 'pl_trandur', 'pl_ratdor', 'pl_ratror', 'sy_vmag', 'sy_kmag']]
target = df1['ttv_flag']

In [18]:
features.columns

Index(['pl_orbper', 'pl_rade', 'pl_orbeccen', 'pl_orbincl', 'pl_tranmid',
       'pl_imppar', 'pl_trandep', 'pl_trandur', 'pl_ratdor', 'pl_ratror',
       'sy_vmag', 'sy_kmag'],
      dtype='object')

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [12]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
# Train a RandomForestClassifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 1.00
Precision: 0.00
Recall: 0.00
F1 Score: 0.00

c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1757: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))

In [14]:
# Sample input data
sample_input = pd.DataFrame({
    'pl_orbper': [10.0],
    'pl_rade': [1.5],
    'pl_orbeccen': [0.1],
    'pl_orbincl': [89.0],
    'pl_tranmid': [2459000.0],
    'pl_imppar': [0.02],
    'pl_trandep': [0.01],
    'pl_trandur': [2.0],
    'pl_ratdor': [0.01],
    'pl_ratror': [0.1],
    'sy_vmag': [10.0],
    'sy_kmag': [8.0]
})

# Standardize the sample input
sample_input_scaled = scaler.transform(sample_input)

# Make predictions using the trained model
sample_output = model.predict(sample_input_scaled)

print("Sample Input:")
print(sample_input)
print("\nPredicted Output:")
print(sample_output)

Sample Input:
   pl_orbper  pl_rade  pl_orbeccen  pl_orbincl  pl_tranmid  pl_imppar  \
0       10.0      1.5          0.1        89.0   2459000.0       0.02

   pl_trandep  pl_trandur  pl_ratdor  pl_ratror  sy_vmag  sy_kmag
0        0.01         2.0       0.01        0.1     10.0      8.0

Predicted Output:
[0]

In [15]:
y_train.nunique()

2

In [16]:
# Select only rows where ttv_flag is 1
class_1_data = df1[df1['ttv_flag'] == 1]

# Display the dataset for class 1
print("Dataset for Class 1:")
print(class_1_data)

Dataset for Class 1:
           pl_name  pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  \
2247      K2-266 d  14.697000   3.400000e-04  -3.500000e-04           0.0
2250      K2-266 e  19.482000   1.200000e-03  -1.200000e-03           0.0
4985   Kepler-11 b  10.303900   6.000000e-04  -1.000000e-03           0.0
5000   Kepler-11 c  13.024100   1.300000e-03  -8.000000e-04           0.0
5011   Kepler-11 d  22.684500   9.000000e-04  -9.000000e-04           0.0
5027   Kepler-11 e  31.999600   8.000000e-04  -1.200000e-03           0.0
5043   Kepler-11 f  46.688800   2.700000e-03  -3.200000e-03           0.0
31250    WASP-18 b   0.941452   2.400000e-07  -2.400000e-07           0.0
31256    WASP-18 b   0.941453   7.800000e-07  -8.600000e-07           0.0

       pl_rade  pl_radeerr1  pl_radeerr2  pl_radelim  pl_orbeccen  ...  \
2247     2.930        0.140       -0.120         0.0      0.04700  ...
2250     2.730        0.140       -0.110         0.0      0.04300  ...
4985     1.800        0.030       -0.050         0.0      0.04500  ...
5000     2.870        0.050       -0.060         0.0      0.02600  ...
5011     3.120        0.060       -0.070         0.0      0.00400  ...
5027     4.190        0.070       -0.090         0.0      0.01200  ...
5043     2.490        0.040       -0.070         0.0      0.01300  ...
31250   13.899        0.886       -0.886         0.0      0.00510  ...
31256   14.202        0.695       -0.504         0.0      0.00848  ...

       pl_ratror  pl_ratrorerr1  pl_ratrorerr2  pl_ratrorlim  sy_vmag  \
2247     0.03827        0.00071       -0.00057           0.0   11.625
2250     0.03564        0.00067       -0.00061           0.0   11.625
4985     0.01563        0.00018       -0.00023           0.0   13.817
5000     0.02496        0.00015       -0.00019           0.0   13.817
5011     0.02714        0.00018       -0.00019           0.0   13.817
5027     0.03643        0.00021       -0.00028           0.0   13.817
5043     0.02169        0.00026       -0.00026           0.0   13.817
31250    0.10180        0.00110       -0.00110           0.0    9.280
31256    0.09576        0.00105       -0.00063           0.0    9.280

       sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2
2247         0.046       -0.046    8.897        0.023       -0.023
2250         0.046       -0.046    8.897        0.023       -0.023
4985         0.092       -0.092   12.180        0.020       -0.020
5000         0.092       -0.092   12.180        0.020       -0.020
5011         0.092       -0.092   12.180        0.020       -0.020
5027         0.092       -0.092   12.180        0.020       -0.020
5043         0.092       -0.092   12.180        0.020       -0.020
31250        0.030       -0.030    8.131        0.027       -0.027
31256        0.030       -0.030    8.131        0.027       -0.027

[9 rows x 48 columns]